services:
  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: todo-container
    restart: always
    ports:
      - "5012:4000"
    environment:
      MONGO: "mongodb://mongo:27017/todo"   
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
